apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - rabbitmq-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ml-worker-deployment.yaml
  - services.yaml
  - ingress.yaml
images:
  - name: docker.io/aristikj/lipid-classifier-backend
    newTag: 71a7b4e948f6b6d56b11f1653e0b02e8f5a9e58a
  - name: docker.io/aristikj/lipid-classifier-frontend
    newTag: 71a7b4e948f6b6d56b11f1653e0b02e8f5a9e58a
  - name: docker.io/aristikj/lipid-classifier-ml-worker
    newTag: 71a7b4e948f6b6d56b11f1653e0b02e8f5a9e58a
