apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - rabbitmq-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ml-worker-deployment.yaml
  - services.yaml
  - ingress.yaml
images:
  - name: docker.io/aristikj/lipid-classifier-backend
    newTag: 0cda787a0183865ad2297e19a244d49a564e573d
  - name: docker.io/aristikj/lipid-classifier-frontend
    newTag: 0cda787a0183865ad2297e19a244d49a564e573d
  - name: docker.io/aristikj/lipid-classifier-ml-worker
    newTag: 0cda787a0183865ad2297e19a244d49a564e573d
