apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - rabbitmq-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ml-worker-deployment.yaml
  - services.yaml
  - ingress.yaml
images:
  - name: docker.io/aristikj/lipid-classifier-backend
    newTag: 152fc30269cbd71a3bd981a56057b1e8d5e61df1
  - name: docker.io/aristikj/lipid-classifier-frontend
    newTag: 152fc30269cbd71a3bd981a56057b1e8d5e61df1
  - name: docker.io/aristikj/lipid-classifier-ml-worker
    newTag: 152fc30269cbd71a3bd981a56057b1e8d5e61df1
