apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lipid-classifier
  namespace: argocd
spec:
  description: Lipid Class Classifier GitOps project
  sourceRepos:
    - https://github.com/andrejwastaken/lipid-class-classifier.git
    - https://charts.bitnami.com/bitnami
  destinations:
    - namespace: lipid-classifier
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
